name: proyek_akhir_kelas_flutter1
description: "Mobile Banking"
  
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4
  
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  intl: ^0.18.0
  flutter_lints: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Quintessential
      fonts:
       - asset: fonts/Quintessential/Quintessential-Regular.ttf
    - family: Staatliches
      fonts:
       - asset: fonts/Staatliches/Staatliches-Regular.ttf
    - family: Oxygen
      fonts:
       - asset: fonts/Oxygen/Oxygen-Regular.ttf
       